securesign/sigstore-ocp

examples/values-ez.yaml
examples/values-sigstore-openshift.yaml

This PR is related to this issue [here](https://github.com/securesign/sigstore-ocp/issues/6) and involves switching the images used in the helm charts from the upstream to the midstream.
1. Pull down this branch.
2. Create a OpenShift cluster, whichever way your prefer.
3. Follow the steps to deploy the charts [here](https://github.com/securesign/sigstore-ocp)
4. Follow the steps to sign and verify [here](https://github.com/securesign/sigstore-ocp/blob/main/sign-verify.md)
I was able to verify images using both value files, but there was some things I noticed when looking at the upstream charts. 
In the midstream I believe we are missing two images, That were not able to be swapped out. 
1.  [Here](https://github.com/sigstore/helm-charts/blob/main/charts/rekor/values.yaml#L25) , An image …

configured stack to use midstream images

---

README.md
examples/values-ez.yaml
examples/values-sigstore-openshift.yaml
keycloak/resources/sigstore-client.yaml
sign-verify.md
templates/cosign-deployment.yaml
values.yaml

This PR relates to this issue [here](https://github.com/securesign/sigstore-ocp/issues/10), and involves adding cosign to the midstream helm charts. 
1. Pull down branch 
2. Launch an open shift cluster
3. Deploy helm charts (make sure to configure BASE_HOSTNAME in values.yaml)
4. Try sign and verify an image (follow the updated steps in sign-verify.md if needed)
**Important: Should not be merged before this [pr](https://github.com/securesign/image-factory/pull/12)**

Add cosign to helm charts

---

examples/values-ez.yaml

Just a small pr, i noticed that when standing up the stack in the logs of the MySQL image in trillian-system namespace there was a constant warning stating that 'mysl'@localhost didn't have access the original command wasn't using the password right

fix for livenessProbe and readinessProbe

---

templates/cluster-monitoring-resources.yaml
templates/namespace.yaml
values.yaml

This pr adds service monitors, rbac and namespace labels for the rekor-system and fulcio-system namespaces, for future monitoring work.
1. Pull down this pr 
2. Stand up stack as normal
3. Navigate to the Metrics section in the openshitf ui
4. You should be able to query the metrics endpoints exposed by the rekor and fulcio servers

add service monitors for metrics

---

.github/workflows/test.yaml
charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/README.md

updating workflow to run with PRs

Update action on pr

---

keycloak/resources/sigstore-client.yaml

Fix for the keycloak configuration. The "aud" field is missing from the token requested by 
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
-d "client_id=<client_id>" \
-d "username=<username>" \
-d "password=<password>" \
-d "grant_type=password" \
-d "scope=openid" \
<oidc_issuer_url>/protocol/openid-connect/token
```
and the sign request fails with
```
ERROR	server/error.go:45	returning with error	{"requestID": "nMNfx_9E", "code": "InvalidArgument", "clientMessage": "There was an error processing the identity token", "error": "oidc: expected audience \"sigstore\" got []"}
```

Add audience to access token

---

keycloak/operator/subscription.yaml
keycloak/resources/keycloak.yaml

- startingCSV from the keycloak subscription to start installation always from HEAD that results in the shorten upgrade path
- remove `spec.http` field that is a feature of the v2alpha1 but not implemented in v1alpha1 (leads to warning)
```
oc create --validate='warn' -f ~/git/sigstore-ocp/keycloak/resources/keycloack.yaml
Warning: unknown field "spec.http"
```

Keycloak resources fix

---

hack/configure-self-signed-cluster.md
sign-verify.md

This enables initializing cosign to point to a TUF root running on a cluster with self-signed certs.
I also changed the `clustercert` directory to match what the fulcio patch file has for a `volumeMount`, though it does require sudo. If the patch file somehow knows where this is without this change, let me know. The cleanest way would be to abstract the path to the clustercert in the patch file but that may be more effort than we want to get into right now.

Add instructions for adding kube-root-ca to local system

---

images/Dockerfile-clientserver

Updates the image refs to the latest image refs from the rhtas-cli-1-0-beta-lhg9z
snapshot.

Update CLI image refs

---

images/Dockerfile-clientserver

I inadvertently removed the `rekor-image` ref name in my last PR

fixup: restore rekor-image ref

---

.tekton/client-server-pull-request.yaml
.tekton/client-server-push.yaml

This change addresses a bug in RHTAP where build pipeline output strings are required to be less than 4k. The previous buildah task was causing our client-server image build to fail.

chore(pipelines): bump buildah image

---

configure-oidc.md

This is a post-installation flow for Google only. This should be updated to include more IdPs and also to set up the IdPs during the first installation.

Add readme for configurable OIDC

---

.tekton/client-server-pull-request.yaml
.tekton/client-server-push.yaml
images/Dockerfile-clientserver

This image moved from the CLI to the Stack application and therefore its image references need to be updated in the RHTAP pipelines.

chore: update image refs in build pipelines

---

.tekton/client-server-push.yaml

Source image builds were only enabled for pull requests. This change also enables them on push.

pipelines: build source image on push

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/README.md
charts/trusted-artifact-signer/templates/segment-backup-cronjob.yaml
charts/trusted-artifact-signer/templates/segment-backup-job-clusterrole.yaml
charts/trusted-artifact-signer/templates/segment-backup-job-clusterrolebinding.yaml
charts/trusted-artifact-signer/templates/segment-backup-job-sa.yaml
charts/trusted-artifact-signer/templates/segment-backup-job.yaml
charts/trusted-artifact-signer/values.schema.json
charts/trusted-artifact-signer/values.schema.tmpl.json
charts/trusted-artifact-signer/values.yaml
grafana/operator/kustomization.yaml
grafana/operator/namespace.yaml
kind/kind-up-test.sh
tas-easy-install.sh

WIP for the nightly metrics scraping, if im missing anything let me know.

Nightly metrics

---

.tekton/client-server-1-0-gamma-pull-request.yaml
.tekton/client-server-1-0-gamma-push.yaml
.tekton/client-server-pull-request.yaml
.tekton/client-server-push.yaml

For push and pull request tekton manifests, `prefetch-input` was already enabled. Adding it for the gamma release component.
/cc @lance 
/cc @tommyd450

enabling prefetched deps and hermetic builds

---

images/Dockerfile-clientserver

libcap-2.48-5.el8 (RHSA-2023:4524: libcap security update (Moderate)) -->  libcap-2.48-9.el9_2.x86_64

bumping image for httpd for CVE

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/README.md
charts/trusted-artifact-signer/templates/segment-backup-job-sa.yaml
charts/trusted-artifact-signer/values.schema.json
charts/trusted-artifact-signer/values.schema.tmpl.json
charts/trusted-artifact-signer/values.yaml
enable-grafana-monitoring.md
grafana/dashboards/dashboard.yaml
grafana/instance/instance.yaml
grafana/operator/operator.yaml
grafana/resources/rolebinding.yaml
grafana/resources/token.yaml
tas-easy-install.sh
tas-grafana-install.sh

re-opening the update monitoring PR https://github.com/securesign/sigstore-ocp/pull/106 against the `relesae-1.0-gamma` branch ! 
/cc @Gregory-Pereira

Monitoring ns rename

---

tas-installer/cmd/install.go
tas-installer/internal/install/install.go
tas-installer/pkg/helm/helm.go
tas-installer/pkg/helm/values-openshift.tmpl
tas-installer/pkg/oidc/type.go

This pr allows for the configuration of an OIDC provider with the tas installer 
```
Installs Trusted Artifact Signer (TAS) on a Kubernetes cluster.
This command performs a series of actions:
1. Initializes the Kubernetes client to interact with your cluster
2. Sets up necessary certificates
3. Configures secrets
4. Deploys TAS to openshift
Usage:
tas-installer install [flags]
Flags:
--chartVersion string      Version of the Helm chart (default "0.1.26")
-h, --help                     help for install
--oidc-client-id string    Specify the OIDC client ID
--oidc-issuer-url string   Specify the OIDC issuer URL e.g for keycloak: https://[keycloak-domain]/auth/realms/[realm-name]
--oidc-type string         Specify the OIDC type
--valuesFile string        Custom values file for chart …
```

Add OIDC Configuration

---

.gitignore

@cooktheryan 
@tommyd450 
`tas-install` binary was pushed to GH, I updated .gitignore & removed it
ptal!

Update .gitignore, remove binary

---

.tekton/client-server-1-0-gamma-pull-request.yaml
.tekton/client-server-1-0-gamma-push.yaml

In the #160 PR the binary cli tools are fetched using `ec image extract`, hence we'll need the buildah task to allow network access.
This should be reverted once we have a better solution for the "too many base images overflow tekton task result" problem.

Disable hermetic builds for cli image workaround

---

images/Dockerfile-clientserver

This avoids the BASE_IMAGE_DIGESTS Tekton task result in the Konflux build pipeline exceeding the maximum size and causing the build to fail.

Use oc image extract for the cli build to reduce the number of source images

---

images/Dockerfile-clientserver

Rather than copy the files and then move them, we can copy them directly to their required location and filename.
Also add some vertical alignment to the long commands for improved readability.

Remove extra mv commands when building client server image

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/values.yaml

/cc @lance
After this change can no longer reproduce the rekor witness issue with gamma branch. Also including the fix for Fulcio deployment in installer script directly, as well as add a templating command to `tas-easy-install.sh`

swapping in productized version of redis

---

tas-installer/cmd/envgen.go

Generated script works, but contains unnecessary escape characters and indentation.
Part of it:
```
#!/bin/bash
export BASE_HOSTNAME=apps.rosa.ji22z-8ghaf-n5s.4l1r.p3.openshiftapps.com
echo "Base hostname = $BASE_HOSTNAME"
export COSIGN_MIRROR=\https://tuf.\apps.rosa.ji22z-8ghaf-n5s.4l1r.p3.openshiftapps.com
export COSIGN_ROOT=\https://tuf.\apps.rosa.ji22z-8ghaf-n5s.4l1r.p3.openshiftapps.com/root.json
export COSIGN_OIDC_ISSUER=\https://keycloak-keycloak-system.\apps.rosa.ji22z-8ghaf-n5s.4l1r.p3.openshiftapps.com/auth/realms/\sigstore
export REKOR_REKOR_SERVER=\https://rekor.\apps.rosa.ji22z-8ghaf-n5s.4l1r.p3.openshiftapps.com
```
This was removed.

Generate script without escape characters and indentation

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/ci/ci-values.yaml
charts/trusted-artifact-signer/templates/tests/test-sign-verify.yaml

@lance Something like this is an easy solution to the mirroring issue, cant really think of any other way, when the time comes this should be uncommented and updated to the new quay images,.

fix: fix-kind-mirroring

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/templates/backfillRedis-cronjob.yaml
charts/trusted-artifact-signer/templates/consoleclidownload-cosign.yaml
charts/trusted-artifact-signer/templates/consoleclidownload-ec.yaml
charts/trusted-artifact-signer/templates/consoleclidownload-gitsign.yaml
charts/trusted-artifact-signer/templates/consoleclidownload-rekor.yaml
charts/trusted-artifact-signer/values.yaml

Opening this pr to this branch, for viability. Since we don't have a GA branch yet

feat: add backfillredis cronjob, fix helm issue

---

charts/trusted-artifact-signer/Chart.yaml
charts/trusted-artifact-signer/README.md
charts/trusted-artifact-signer/templates/rekor-ui-deployment.yaml

This PR adds the required environment variable in order for the `rekor-search-ui` to be able to issue requests to the Rekor server.
Original PR: https://github.com/securesign/sigstore-ocp/pull/204
Testing with the following container image for the rekor search UI: `quay.io/kahboom/rekor-search-ui@sha256:68a21610cd7de9c34466fed181fb3b26e527906e194f90657ab3c785b2151c85`
Instructions for testing: https://gist.github.com/kahboom/3294d64b5186b3c79b68bd78923ebec5

feat(config): add rekor endpoint env var
