securesign/sigstore-ocp

examples/values-ez.yaml, examples/values-sigstore-openshift.yaml
Quick fix to change the sha's for the image versions to the tags
=> swap shas for images to fix update issues

charts/scaffolding/Chart.yaml, charts/scaffolding/README.md, charts/scaffolding/README.md.gotmpl, enable-grafana-monitoring.md, grafana/dashboards/kustomization.yaml
few small fixes after the last 2 merges
=> few small fixes

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/values.yaml
All of the RHTAP images relevant to this have been added as far as I am aware.
The Rekor Server Image needs to be adjusted since last I checked.
I will follow up with another small pr once the Rekor Server Image has been corrected.
=> RHTAP Images

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/values.yaml
Images built from our RHTAS workspace in RHTAP.
=> Rhtas images

README.md, charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/values.yaml, quick-start-with-keycloak.md
typo and updated the helm release namespace
=> typo & name change

fulcio-create-root-ca-openssl.sh
Added keyusage to Fulcio generation
=> Added keyusage to Fulcio generation

quick-start-with-keycloak.md, tas-easy-install.sh
Authored by: Veda Shankar <veda.shankar@redhat.com>
Signed-off-by: Lily Sturmann <lsturman@redhat.com>
=> Add easy install script

.github/workflows/test.yaml, charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/values.yaml
testing registry auth & removing a comment
=> remove comment

tas-easy-install.sh
Added the function to generate the script for initializing the Sigstore environment variables. The function will be called at the end of the script.
=> adding script for env variable initialization

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, keycloak-example.md, keycloak/resources/example-user.yaml
add example to add keycloak user
=> add docs to create new keycloak user

charts/trusted-artifact-signer/README.md
=> pre-commit run --all-files

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/templates/_helpers.tpl, charts/trusted-artifact-signer/templates/clientserver-deployment.yaml, charts/trusted-artifact-signer/templates/cosign-deployment.yaml, charts/trusted-artifact-signer/templates/segment-backup-cronjob.yaml, charts/trusted-artifact-signer/templates/segment-backup-job-clusterrole.yaml, charts/trusted-artifact-signer/templates/segment-backup-job-clusterrolebinding.yaml, charts/trusted-artifact-signer/templates/segment-backup-job-sa.yaml, charts/trusted-artifact-signer/templates/segment-backup-job.yaml, charts/trusted-artifact-signer/values.schema.json, charts/trusted-artifact-signer/values.schema.tmpl.json, charts/trusted-artifact-signer/values.yaml, grafana/operator/kustomization.yaml, grafana/operator/namespace.yaml, kind/kind-up-test.sh, tas-easy-install.sh
Backporting from main
/cc @ppecka @osmman
=> Adds monitoring to release-1.0.beta

.tekton/client-server-1-0-gamma-pull-request.yaml, .tekton/client-server-1-0-gamma-push.yaml, .tekton/client-server-push.yaml
/cc @lance and /cc @tommyd450  PTAL
=> Client-server enable source builds for Release 1.0.gamma 

examples/values-kind-byodb.yaml, examples/values.yaml
Allow for a user to provide values for a database that is not deployed by the installer.
=> Capabilities to provide values for a managed database

charts/trusted-artifact-signer/templates/consoleclidownload-cosign.yaml, charts/trusted-artifact-signer/templates/consoleclidownload-gitsign.yaml, charts/trusted-artifact-signer/templates/consoleclidownload-rekor.yaml, images/Dockerfile-clientserver
Adding the new architecture cli-images to the client server. If we want to do a different folder structure let me know!
=> Updating CLI Server to have more architectures

tas-initializer/tas-initializer.sh
Corrections to tas-initializer script to create the expected rekor and fulcio secret
=> Corrections to tas-initializer script

charts/trusted-artifact-signer/templates/segment-backup-job-clusterrole.yaml, charts/trusted-artifact-signer/templates/segment-backup-job-clusterrolebinding.yaml, charts/trusted-artifact-signer/templates/segment-backup-job-sa.yaml, charts/trusted-artifact-signer/templates/tas-pull-secret.yaml, charts/trusted-artifact-signer/values.yaml
=> enabling namespace configuration and name for SBJ

docs/sign-verify.md
No changes need to be made to the tas-installer for the install to work on windows, this pr just adds some docs related to signing and verifying on windows.
=> SECURESIGN-186 | Add docs for signing on windows

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/templates/cosign-deployment.yaml, charts/trusted-artifact-signer/templates/tests/test-sign-verify.yaml, docs/configure-oidc.md, docs/sign-verify.md, tas-easy-install.sh
@sabre1041 pulled in your commit for updating env vars, also
=> Update to use sigstore env variables everywhere instead of flags

images/Dockerfile-clientserver
=> fix-cosign-amd64.gz-image

images/Dockerfile-clientserver
=> update gitsign image

images/Dockerfile-clientserver
Ref: https://issues.redhat.com/browse/EC-292
=> Add ec cli binaries to the cli download image

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/values.yaml, tas-easy-install.sh
Small pr to resolve the issue with fulcio create certs
=> add cert check

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/values.yaml
PLEASE READ.
I have not had the chance to test these just yet so if you have the time try an install thanks in advance.
=> Updating with Current Snapshots

release-plans/gamma/ReleasePlan.yaml
=> release plan for gamma access

.gitignore, tas-easy-install.sh, tas-env-variables.sh
=> bring tas-env-generate script into single source of truth

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md
@Gregory-Pereira merge this bump into `gamma-into-main` branch, then let's run through the test suite
=> bump chart version

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/ci/ci-values.yaml, charts/trusted-artifact-signer/templates/cosign-deployment.yaml, charts/trusted-artifact-signer/templates/tests/test-sign-verify.yaml, docs/sign-verify.md, examples/values-kind-byodb.yaml, examples/values-kind-sigstore.yaml, examples/values-sigstore-openshift-byo-fulcio-root.yaml, examples/values-sigstore-openshift-byo-rekor-key.yaml, examples/values-sigstore-openshift.yaml, examples/values.yaml, keycloak/operator/base/subscription.yaml, keycloak/resources/base/kustomization.yaml, keycloak/resources/base/realm.yaml, keycloak/resources/base/tas-client.yaml, keycloak/resources/base/user.yaml, keycloak/resources/overlay/kind/realm_patch.yaml, tas-env-variables.sh, tas-installer/cmd/envgen.go, tas-installer/pkg/helm/values-openshift.tmpl
=> Update keycloak tas env vars

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/templates/clientserver-deployment.yaml, charts/trusted-artifact-signer/values.yaml
Pr to reflect the split of the client server
=> client server changes

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/values.yaml
Updating the images to the latest snapshots.
=> chore: GA Images

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/values.yaml
=> GA: update-images

charts/trusted-artifact-signer/Chart.yaml, charts/trusted-artifact-signer/README.md, charts/trusted-artifact-signer/templates/segment-backup-job-clusterrole.yaml, charts/trusted-artifact-signer/values.yaml
Need to check configmaps plus `console.operator.openshift.io cluster`
=> adding ability to check configmaps for SBJ

docs/sts/aws-sts-sa.yaml, docs/sts/aws-sts.md, docs/sts/cosign-dep.yaml
This adds the docs for setting up fulcio to use AWS STS OIDC identity provider
=> add aws sts docs

tas-env-variables.sh
Support for both Helm and Operator based RHTAS deployments
=> Updates to environment variable sourcing script
